variables:
  ###########################################################################################################################
  ################################################## Common Variables #######################################################
  ###########################################################################################################################

  # Enable or disable CARMLs CI telemetry tracking. Note: This tracks the number of deployments only.
  # See: https://github.com/Azure/ResourceModules/wiki/The%20library%20-%20Module%20design#telemetry
  enableDefaultTelemetry: true

  ########################
  ##   Token settings   ##
  ########################

  # the 'localToken_' prefix will be removed from the key name when the pipelines run.
  # e.g. if you have a token in your parameter file as <<customKey>>, then the token defined in this file looks like "localToken_customKey": 'value'
  localToken_namePrefix: '' # A 3-5 character length unique string, included in the resources names (e.g. 'cntso'). Used for local module testing and pipelines.

  # this determines the starting prefix and ending suffix of the token in your file.
  tokenPrefix: '<<'
  tokenSuffix: '>>'

  ########################
  ##   Agent settings   ##
  ########################

  vmImage: 'ubuntu-latest' # Use this for Microsoft-hosted agents
  poolName: '' # Use this for self-hosted agents

  #######################################
  ##   Common folders and file paths   ##
  #######################################

  moduleTestFilePath: 'utilities/pipelines/staticValidation/module.tests.ps1'

  #############################
  ##   Validation settings   ##
  #############################

  # Static validation #
  # ----------------- #

  allowPreviewVersionsInAPITests: true # When enabled, preview versions do not fail the API version tests in the `module.tests.ps1` file

  # Deployment validation #
  # --------------------- #

  location: 'Australia East' # The default location to test deploy resources to

  #############################
  ##   Publishing settings   ##
  #############################

  # Shared settings #
  # --------------- #

  publishLatest: true # [Only for Template-Specs & Bicep Registry] Publish an absolute latest version. Note: This version may include breaking changes and is not recommended for production environments

  # Template-Spec settings #
  # ---------------------- #

  templateSpecsDoPublish: true # Set to true, if you would like to publish module templates as template specs
  templateSpecsRGName: 'overlays-rg' # The name of the resource group to publish to. If the resource group does not exist, it will be created.
  templateSpecsRGLocation: 'Australia East' # The location of the resource group to publish to
  templateSpecsDescription: components # The description to add to template specs published by this platform

  # ------------------------------- #
  # Private Bicep Registry settings #
  # ------------------------------- #

  bicepRegistryDoPublish: true # Set to true, if you would like to publish module templates to a bicep registry
  bicepRegistryName: ahmadcarmldemooverbr # The name of the bicep registry (ACR) to publish to. If it does not exist, it will be created.
  bicepRegistryRGName: 'overlays-rg' # The resource group that hosts the private bicep registry (ACR)
  bicepRegistryRgLocation: 'Australia East' # The location of the resource group to publish to

  ###########################################################################################################################
  ################################################## Azure DevOps Only ######################################################
  ###########################################################################################################################

  #############################
  ##   Connection settings   ##
  #############################

  serviceConnection: 'CARML-CSU-Tenant-Connection'

  ################
  ##   Source   ##
  ################

  vstsOrganizationURI: '$(System.CollectionUri)' # The URI of the TFS collection or Azure DevOps organization. For example: https://dev.azure.com/fabrikam/.
  vstsProject: '$(System.TeamProject)'
  modulesRepository: ResourceModules # The repository hosting the deployment code (i.e. 'Components'). MUST be provided as a variable with every pipeline
  pipelineFunctionsPath: 'utilities/pipelines'

  #############################
  ##   Publishing settings   ##
  #############################

  # Universal packages settings #
  # --------------------------- #

  artifactsFeedDoPublish: true # Set to true, if you would like to publish modules as Universal Packages (in Azure DevOps Artifacts)
  vstsFeedName: 'carml' # The name of the Azure DevOps universal packages feed to publish to
  vstsFeedProject: '$(System.TeamProject)' # The project that hosts the feed
  vstsFeedToken: $(System.AccessToken) # The token used to publish universal packages into the feed above

  #################################
  #   Azure PowerShell Version   ##
  #################################

  # Should be set to 'latestVersion' unless there is an issue with the Az PowerShell modules.
  # If a specific version needs to be set azurePowerShellVersion should be changed to 'OtherVersion'.
  # NOTE: The strings are case sensitive and will not work unless properly entered.
  azurePowerShellVersion: 'latestVersion'
  # If using the latest version of the Az PowerShell modules, set `preferredAzurePowerShellVersion` to an empty string ''.
  # If overriding the Az PowerShell module version, set to the version. Example: '4.4.0'
  preferredAzurePowerShellVersion: ''
#
# NOTE: To override for just an individual template, just add the following to the
#     templates pipeline.yml replacing '4.4.0' with the desired version:
#
#   - name: azurePowerShellVersion
#     value: 'OtherVersion'
#   - name: preferredAzurePowerShellVersion
#     value: '4.4.0'
#
